spring:
  security:
    oauth2:
      client:
        registration:
          vas3k-reg:
            provider: "vas3k-provider"
            authorization-grant-type: "authorization_code"
            scope:
              - "openid"
        provider:
          vas3k-provider:
            issuer-uri: "https://vas3k.club"

  jpa:
    open-in-view: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog.xml"
    drop-first: false

app:
  userinfo:
    url: "https://vas3k.club/user/me.json"